LIB = libads

#include ../Makefile.config
#include ../Makefile.options

OBJECTS = \
	ads1115.o \

DEPS += \
	libmsp \

override SRC_ROOT = ../../src

override CFLAGS += \
	-I$(SRC_ROOT)/include \
	-I$(SRC_ROOT)/include/$(LIB) \
